name: Tests

on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pip install pipenv
      - name: Install development dependencies
        run: pipenv install --system --dev
      - name: Download german spacy model
        run: python -m spacy download de_core_news_lg
      - name: Run tests
        run: pipenv run test
